github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Soteria]
description: [Eclipse EE4J implementation of Jakarta Security]

links:
  source: https://github.com/eclipse-ee4j/soteria
  javadocs: docs/api/
  issues_url: site.github.issues_url
  download: https://github.com/eclipse-ee4j/soteria/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/soteria-dev
  # faq: FAQ

include:
  - LICENSE.md
  - CONTRIBUTING.md